apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kong-apis.henrik.dk
spec:
  group: henrik.dk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                port:
                  type: integer
                swagger:
                  type: string
  names:
    kind: KongApi
    plural: kong-apis
    singular: kong-api
    shortNames:
      - ka
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kong-api-data.henrik.dk
spec:
  group: henrik.dk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string
                updated:
                  type: string
  names:
    kind: KongApiData
    plural: kong-api-data
    shortNames:
      - kaj
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kong-api-configs.henrik.dk
spec:
  group: henrik.dk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                termsUrl:
                  type: string
                contactEmail:
                  type: string
                licenseName:
                  type: string
                licenseUrl:
                  type: string
                securityScheme:
                  type: string
                securityKeyName:
                  type: string
  names:
    kind: KongApiConfig
    plural: kong-api-configs
    shortNames:
      - kac
  scope: Namespaced
