apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kong-portal-controller.fullname" . }}
rules:
- apiGroups: ['henrik.dk']
  resources: ['*']
  verbs: ['*']
- apiGroups:
    - ''
  resources: ['services', 'pods']
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kong-portal-controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kong-portal-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kong-portal-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
