apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kong-portal-controller.serviceAccountName" . }}
  labels:
    {{- include "kong-portal-controller.controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
