{{- if .Values.portal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-portal-controller.portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kong-portal-controller.portal.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "kong-portal-controller.portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.portal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-portal-controller.portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.portal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-portal-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.portal.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "kong-portal-controller.portal.fullname" . }}
          securityContext:
            {{- toYaml .Values.portal.securityContext | nindent 12 }}
          image: {{ .Values.portal.image.url }}
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          resources:
            {{- toYaml .Values.portal.resources | nindent 12 }}
          env:
            - name: namespace
              value: {{ .Values.portal.lookupNamespace }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      {{- with .Values.portal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}