{{- if .Values.portal.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-portal-controller.portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kong-portal-controller.portal.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    {{- include "kong-portal-controller.portal.selectorLabels" . | nindent 4 }}
{{- end }}