apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "skooner-lite.fullname" . }}
rules:
- apiGroups:
  - "*"
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - pods
  - pods/log
  - pods/status
  - poddisruptionbudgets  
  - services
  - services/proxy
  - deployments
  - deployments/scale
  - daemonsets
  - replicasets
  - replicasets/scale
  - replicationcontrollers
  - replicationcontrollers/status
  - replicationcontrollers/scale  
  - statefulsets
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - ingresses
  - networkpolicies
  - limitranges
  - bindings
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
  - proxy
- nonResourceURLs:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "skooner-lite.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "skooner-lite.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "skooner-lite.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
